// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace E2ETests;

public class TestData
{
    public static readonly string[] AccountingCategories =
    {
        "Current Assets: Cash",
        "Current Assets: Petty Cash",
        "Current Assets: Accounts Receivable",
        "Current Assets: Inventory",
        "Current Assets: Prepaid Expenses",
        "Current Assets: Other",
        "Fixed Assets: Buildings",
        "Fixed Assets: Land",
        "Fixed Assets: Leasehold Improvements",
        "Fixed Assets: Equipment",
        "Fixed Assets: Furniture",
        "Fixed Assets: Software",
        "Fixed Assets: Hardware",
        "Fixed Assets: Patents",
        "Fixed Assets: Goodwill",
        "Fixed Assets: Other",
        "Current Liabilities: Accounts Payable",
        "Current Liabilities: Accrued Expenses",
        "Current Liabilities: Credit Card Fees",
        "Current Liabilities: Payroll Taxes",
        "Current Liabilities: Taxes Payable",
        "Current Liabilities: Unearned Revenue",
        "Current Liabilities: Other",
        "Long-Term Liabilities: Bonds Payable",
        "Long-Term Liabilities: Loans Payable",
        "Long-Term Liabilities: Mortgage Payable",
        "Equity: Common Stock",
        "Equity: Paid-in Capital",
        "Sales: Sales",
        "Sales: Returns and Allowances",
        "Service Revenue: Royalties",
        "Service Revenue: Other",
        "Expenses: Cost of Goods Sold",
        "OpEx: Advertising",
        "OpEx: Amortization",
        "OpEx: Audit Fees",
        "OpEx: Bad Debt",
        "OpEx: Bank Charges",
        "OpEx: Business Insurance",
        "OpEx: Consulting Fees",
        "OpEx: Depreciation",
        "OpEx: Donations",
        "OpEx: Entertainment",
        "OpEx: Freight and Shipping",
        "OpEx: Gas and Electricity",
        "OpEx: Insurance",
        "OpEx: Interest Expense",
        "OpEx: Legal Fees",
        "OpEx: Licenses and Permits",
        "OpEx: Maintenance and Repairs",
        "OpEx: Marketing",
        "OpEx: Meals and Entertainment",
        "OpEx: Merchant Account Fees",
        "OpEx: Other Expenses",
        "OpEx: Office Supplies",
        "OpEx: Property Taxes",
        "OpEx: Rent Expense",
        "OpEx: Supplies",
        "OpEx: Telephone",
        "Transportation: Air",
        "Transportation: Rail",
        "Transportation: Road",
        "Utilities: Website Hosting Fees",
        "Utilities: Warranty Expense",
        "Utilities: Workers' Compensation Insurance",
        "Payroll Expenses: Employee Salaries",
        "Payroll Expenses: Employee Benefits",
        "Payroll Expenses: Employee Payroll Taxes",
        "Payroll Expenses: Pension Plans",
        "Payroll Expenses: Workers' Compensation Insurance",
    };
}
